### ISSUE TITLE
When?

### ISSUE THREAD

**Issue by tydiamond11** [bitfocus/companion-module-vimeo-livestreamstudio6#1]
When will this be placed into the main companion software?

**Comment by ChgoChad** [comment]
> When will this be placed into the main companion software?

We are in final beta testing of the module right now.  I will be submitting the module for inclusion in the main Companion code base in the next couple of weeks.  Once submitted, hopefully it gets merged into the main code base right away, but I have seen it take longer. 

In the meantime if you want to participate in the beta of the module, let me know and I will send you the details to download a custom build that includes the module.
