### ISSUE TITLE
help wanted

### ISSUE THREAD

**Issue by PhilipHamilton** [bitfocus/companion-module-vimeo-livestreamstudio6#3]
I could really use this instance/module for something I'm working on now.
How and where does this module get installed in companion?
I don't see this instance/module in the list that companion offers in it's install by category or manufacturer.

**Comment by ChgoChad** [comment]
Philip -
 You have to go under the Companion Beta builds section of their website.   Only Companion Beta builds ver 2.2.0 or later.

You can find the beta builds on Companions website here:
https://bitfocus.io/companion/download/builds/

Let me know of you have any other questions.
________________________________
From: PhilipHamilton ***@***.***>
Sent: Wednesday, March 9, 2022 2:13:06 PM
To: bitfocus/companion-module-vimeo-livestreamstudio6 ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [bitfocus/companion-module-vimeo-livestreamstudio6] help wanted (Issue #3)


I could really use this instance/module for something I'm working on now.
How and where does this module get installed in companion?
I don't see this instance/module in the list that companion offers in it's install by category or manufacturer.

**Comment by PhilipHamilton** [comment]
Thanks, the functionality I wanted works with the beta companion through emulator or a companion dedicated stream deck.
The other 1/2 of my workflow requires a stream deck button.
Now I can't put a companion button on the stream deck. This stopped working when I made the switch to beta.
I now get a fail to communicate message.
Still stuck.

**Comment by stevespaw** [comment]
<img width="578" alt="image" src="https://user-images.githubusercontent.com/11045430/157737066-0831539b-5aab-445a-be38-31ae3c30677c.png">

**Comment by PhilipHamilton** [comment]
Thanks Steve,

You were right on the problem.

Different issue:
I built a Multi Action button that only works every second time???

Any advice on what is going on with that?

Philip Hamilton

P. Hamilton Audio Visuals Inc.
320 St-Louis Ave
Pointe Claire, Quebec, H9R 4V9

  (514) 332-6440 (Phone office)
  ***@***.*** (E-mail)
