### ISSUE TITLE
GFX row selection before pushing to program

### ISSUE THREAD

**Issue by thommoser** [bitfocus/companion-module-vimeo-livestreamstudio6#4]
I like this module and use it every week. One improvement request I do have.

If possible, it would be nice if you could also trigger a specific row before pushing a GFX to the program. That would be very helpful for cases like lower thirds and so on.

Is that possible to implement?
Thanks in advance.

**Comment by ChgoChad** [comment]
_[ Sorry for the extreme delay in responding, I was not getting the notification. ]_   

To answer your question: Unfortunately selecting a graphics row is **not** something that is available to control via the network API in Livestream Studio.   I really wish there was a way to control that, but there is no way. Livestream would have to change their code and implement that ability.

**Comment by PhilipHamilton** [comment]
Hi Chad,

Thank you for the answer.

Regards,

Philip Hamilton

P. Hamilton Audio Visuals Inc.
320 St-Louis Ave
Pointe Claire, Quebec, H9R 4V9

  (514) 863-1981 (Cell)
  ***@***.*** (E-mail)
