### ISSUE TITLE
Updated to Companion v3 Compatability

### ISSUE THREAD

**Issue by matthewbeamish** [bitfocus/companion-module-vimeo-livestreamstudio6#5]
Will this plugin be able updated to be compatible with Companion v3? Right now, it states this plugin is not compatible and there are obvious bugs within the functionality when using this plugin with Companion v3.

**Comment by ChgoChad** [comment]
Hi, Matthew.  Thanks for reaching out.  I am planning on porting this module to Companion v3 in the very near future.  However, currently there are no functionality issues with running this module in its current state on Companion v3.  I run **Companion v3.11** and have no problems controlling  nb Studio.  

One thing to note is that any source button that is in the presets folder or has been added to a button page will not show the name of the source you set until Livestream transmits a source config refresh. You'll notice this issue after setting up buttons to control Livestream and then restarting the system running companion.   To force Livestream to update source names in companion you can do the following: In Livestream under the **INPUT** tab, click a source and drag to rearrange the order of inputs in the list and then immediately drag the list back to its original order. . Changing the order of the inputs in that list will force the names to be sent to Companion. This is a common issue that can happen and cause the module to appear like it's malfunctioning. 

**Can you elaborate on what issues you are experiencing and I will see if I help you out?**
